### ISSUE TITLE
Question: How to add stop directive to an action?

### ISSUE THREAD

**Issue by synaptis** [voxpupuli/puppet-rsyslog#110]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Distribution: CentOS 7
- Module version: 3.3.0

## How to reproduce (e.g Puppet code you use)

I am attempting to re-create the following legacy config via this module:
```
$ActionQueueFileName fwdRule1
$ActionQueueMaxDiskSpace 1g
$ActionQueueSaveOnShutdown on
$ActionQueueType LinkedList
$ActionResumeRetryCount -1
local0.* @syslog.domain.internal:514
& stop
```
The rainerscript equivalent should look like this:
```
local0.*                       action(type="omfwd"
                                           queue.filename="fwdRule1"
                                           queue.maxDiskSpace="1g"
                                           queue.saveOnShutdown="on"
                                           queue.type="LinkedList"
                                           action.resumeRetryCount="-1"
                                           target="syslog1.resources.internal"
                                           port="514"
                                     )

  stop
```

I think this hiera configuration is almost there:
```
syslog::server::actions:
  http_logs:
    type: omfwd
    facility: 'local0.*'
    config:
      queue.filename: 'fwdRule1'
      queue.maxDiskSpace: '1g'
      queue.saveOnShutdown: 'on'
      queue.type: 'LinkedList'
      action.resumeRetryCount: '-1'
      target: 'syslog.domain.internal'
      port: '514'
```

How can I add the 'stop' directive after the action?

**Comment by dhollinger** [comment]
Currently we don't have any way to add that outside of the `custom_config`. In fact, I didn't know that was possible as my experience with rsyslog always had us discarding (`stop`) as part of a custom ruleset.

It shouldn't be too difficult to add. I'll look into it

**Comment by dhollinger** [comment]
@synaptis I did some research and adding support for what you want will work and is fairly simple, however if I place the option in there and it is activated, placing the `stop` after the action args AND the action is **not** the **final** config in the file (AKA default ruleset), you **will** see this error:

```
rsyslogd: version 8.32.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during config processing: STOP is followed by unreachable statements!  [v8.32.0 try http://www.rsyslog.com/e/2207 ]
```

As such, I will probably refrain from adding this functionality and direct you to placing any actions that need a stop within a custom ruleset to prevent it from interfering with the rest of the configuration.

@bastelfreak @crayfishx @alexjfisher - thoughts on the above statement?

**Comment by dhollinger** [comment]
@synaptis I should probably give an example of what my suggestion looks like:

``` yaml
syslog::server::rulesets:
  action_http_logs:
    rules:
      - action:
          name: http_logs
          type: omfwd
          facility: 'local0.*'
          config:
            queue.filename: 'fwdRule1'
            queue.maxDiskSpace: '1g'
            queue.saveOnShutdown: 'on'
            queue.type: 'LinkedList'
            action.resumeRetryCount: '-1'
            target: 'syslog.domain.internal'
            port: '514'
    stop: true
```

**Comment by synaptis** [comment]
@dhollinger Thanks for looking into this. I'll admit that my knowledge of syslog has been challenged and improved by implementing this module so the config I was trying to use may not have been optimal although it was working for us. I agree that introducing features that can easily cause errors is not a good idea.

Cheers also for your suggested config, I had worked around the problem using the conditional below  which I think will have a similar effect but I will test out your suggestion also.
```
rsyslog::server::expression_filters:
  httpd_logs:
    conditionals:
      if:
        expression: '$syslogfacility-text == "local0"'
        tasks:
          - action:
              type: omfwd
              facility: 'local0.*'
              config:
                queue.filename: 'fwdRule1'
                queue.maxDiskSpace: '1g'
                queue.saveOnShutdown: 'on'
                queue.type: 'LinkedList'
                action.resumeRetryCount: '-1'
                target: 'syslog1.resources.internal'
                port: '514'
          - stop: true
```

I'm happy for this to be closed or to close it myself if that's the process.
