### ISSUE TITLE
Ruleset expression filter: problem with documention

### ISSUE THREAD

**Issue by christopher-b** [voxpupuli/puppet-rsyslog#112]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.2.0
- Ruby: 2.5.3
- Distribution: Ubuntu 16.04
- Module version: 3.3.0

## How to reproduce (e.g Puppet code you use)
Straight from the documentation for ruleset expression filters: 
```
rsyslog::server::rulesets:
  ruleset_eth0_514_udp:
    parameters:
      queue.type: LinkedList
    rules:
      - expression_filter:
          if:
            expression: '$fromhost-ip == "192.168.255.1"'
            tasks:
              - call: "ruleset.action.rawlog.standard"
              - stop: true
      - call: "ruleset.client.log.standard"
      - call: "ruleset.unknown.standard"
```

## What are you seeing
An error message.

## What behaviour did you expect instead
No error :)

## Output log
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Method call, 'each' expects one of:
  (Hash hash, Callable[2, 2] block)
    rejected: parameter 'hash' expects a Hash value, got Undef
  (Hash hash, Callable[1, 1] block)
    rejected: parameter 'hash' expects a Hash value, got Undef
  (Iterable enumerable, Callable[2, 2] block)
    rejected: parameter 'enumerable' expects an Iterable value, got Undef
  (Iterable enumerable, Callable[1, 1] block)
    rejected: parameter 'enumerable' expects an Iterable value, got Undef (file: /etc/puppetlabs/code/environments/production/modules/rsyslog/templates/expression_filter.epp, line: 6, column: 18) (file: /etc/puppetlabs/code/environments/production/modules/rsyslog/manifests/config/rulesets.pp, line: 3) on node canvasci-its.ocad.ca
```

## Any additional information you'd like to impart
It seems that the module is expecting an additional key that is not present in the documention. The following *will* work: 
```
rsyslog::server::rulesets:
  ruleset_eth0_514_udp:
    parameters:
      queue.type: LinkedList
    rules:
      - expression_filter:
          filter:
            if:
              expression: '$fromhost-ip == "192.168.255.1"'
              tasks:
                - call: "ruleset.action.rawlog.standard"
                - stop: true
      - call: "ruleset.client.log.standard"
      - call: "ruleset.unknown.standard"
```
Note the addition of the `filter` key below `expression_filter`. I'm not sure if the filter key needs to be added to the docs, or if https://github.com/voxpupuli/puppet-rsyslog/blob/4541539f3a7a22bde20a6e4c046b0246db1d9109/templates/ruleset.epp#L18 needs to be updated to remove the reference to the filter key. 

Thanks!
