### ISSUE TITLE
How to use conditions ?

### ISSUE THREAD

**Issue by hdep** [voxpupuli/puppet-rsyslog#117]
Hi,

for my central syslog server I need to add some logic to send clients logs into a specific file, and to send system logs into classic path.

I found a way to do this with rsyslog syntax : 

```
if $hostname == 'myserver' then {
# local config goes here
} else
{
# remote_filter send logs to specific path
*.*     ?remote
}
```

The issue is I don't have any idea on how to do this with the module.
Any idea ?

**Comment by dhollinger** [comment]
@hdep Sorry for the delay in replying, I haven't had time to look at issues lately. Unfortunately, at this time we don't support what the Rsyslog (and module params) call "Legacy config" within our conditional expression component. You'd need to use the `rsyslog::server::custom_config` parameter.

```yaml
rsyslog::server::custom_config:
  classic_path_condition:
    priority: 45 # Or whatever you need the priority to be. 45 is the default for custom_config
    content: |
      if $hostname == 'myserver' then {
      # local config goes here
      } else {
      # remote_filter send logs to specific path
      *.*     ?remote
      }
```

**Comment by hdep** [comment]
Hi @dhollinger,

thank you for the feedback ! 

I manage to do like this : 

```
rsyslog::server::templates:
  remote:
    type: string
    string: "/applis/log/rsyslog.log"
rsyslog::server::property_filters:
  hostname_filter:
    property: hostname
    operator: '!isequal'
    value: logserver
    tasks:
      - action:
          name: 'Filter syslog from network'
          type: omfile
          facility: "*.*"
          config:
            dynaFile: "remote"
      - stop: true
```
this code on the rsyslog server will store remote logs into remote template.
