### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by negast** [voxpupuli/puppet-rsyslog#127]
Hello
 I'm getting cyclic dependency issues when doing a new install (RHEL7).

I copied the yaml file from the example:
```yaml
rsyslog::client::global_config:
  FileOwner:
    value: 'root'
    type: legacy
 ......
rsyslog::client::modules:
    imuxsock: {}
    imklog: {}
    
rsyslog::client::legacy_config:
  auth_priv_rule:
    key: "auth,authpriv.*"
    value: "/var/log/auth.log"
    .....
 ```

In my profiles I included the following

```puppet
include rsyslog::client
```

When running on the node It gave me the  following:
```
Error: Found 1 dependency cycle:
(Concat_file[/etc/rsyslog.d/50_rsyslog.conf] => Concat[/etc/rsyslog.d/50_rsyslog.conf] => Rsyslog::Generate_concat[rsyslog::concat::module::imuxsock] => Concat::Fragment[rsyslog::component::module::imuxsock] => Concat_fragment[rsyslog::component::module::imuxsock] => Concat_file[/etc/rsyslog.d/50_rsyslog.conf])\nCycle graph written to /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot.
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```

Here is the .dot file content
```dot
digraph Resource_Cycles {
  label = "Resource Cycles"
"Concat_file[/etc/rsyslog.d/50_rsyslog.conf]" -> "File[/etc/rsyslog.d/50_rsyslog.conf]" -> "Concat[/etc/rsyslog.d/50_rsyslog.conf]" -> "Rsyslog::Generate_concat[rsyslog::concat::module::imuxsock]" -> "Concat::Fragment[rsyslog::component::module::imuxsock]" -> "Concat_fragment[rsyslog::component::module::imuxsock]" -> "Concat_file[/etc/rsyslog.d/50_rsyslog.conf]"
"Concat_file[/etc/rsyslog.d/50_rsyslog.conf]" -> "Concat[/etc/rsyslog.d/50_rsyslog.conf]" -> "Rsyslog::Generate_concat[rsyslog::concat::module::imuxsock]" -> "Concat::Fragment[rsyslog::component::module::imuxsock]" -> "Concat_fragment[rsyslog::component::module::imuxsock]" -> "Concat_file[/etc/rsyslog.d/50_rsyslog.conf]"
}
```

I fixed this by removing the before statement from the component/module.pp file
**/rsyslog/manifests/component/module.pp line 21**

```puppet
rsyslog::generate_concat { "rsyslog::concat::module::${name}":
    confdir => $confdir,
    target  => $target,
   (-)  before  => Concat::Fragment["rsyslog::component::module::${name}"],
  }
```
