### ISSUE TITLE
Can't create an expressión filter with more than one 'else if'

### ISSUE THREAD

**Issue by amateo** [voxpupuli/puppet-rsyslog#164]
Hi,

I need to create a ruleset with a rule with an expression with more than just one `else if`. Somethin like:
```
if $hostname == ["sip", "proxysipint", "proxysipintb" ] then {
  set $.filename = "kam-int.log";

    }
else if $hostname == ["sipext", "proxysipext" ] then {
  set $.filename = "kam-ext.log";

    }
else if $hostname == ["pbxum", "pbxum1", "pbxum1b"] then {
  set $.filename = "ast-core.log";

    }
```

So, my code is like:
```yaml
  - expression_filter:
      filter:
        if:
          expression: '$hostname == ["sip", "proxysipint", "proxysipintb" ]'
          tasks:
            - set:
                '$.filename': '"kam-int.log"'
        'else if':
          expression: '$hostname == ["sipext", "proxysipext" ]'
          tasks:
            - set:
                '$.filename': '"kam-ext.log"'
        'else if':
          expression: '$hostname == ["pbxum", "pbxum1", "pbxum1b"]'
          tasks:
            - set:
                '$.filename': '"ast-core.log"'
```
the problem with this hiera is that I have to use the same `else if` key for two different hash elements, so the second overrides the first.

I've been looking for a way to create such an expression, but as the template for an expression is:
```
<%- |
$filter_name,
$conditionals
| -%>
# <%= $filter_name %>
<%- $conditionals.each |$conditional, $options| { -%>
  <%- if $conditional == 'else' { -%>
<%= $conditional %> {
  <%- } else { -%>
<%= "${conditional} ${options['expression']} then" %> {
  <%-}-%>
<%- $options['tasks'].each |$task| { -%>
<%= epp('rsyslog/tasks.epp', { 'tasks' => $task }) -%>
<%-}-%>
}
<%}-%>
```
I can't find any way to do it, because the conditional clause is taken always from the key of the element in the hash.

Is there any way to create such config?

**Comment by amateo** [comment]
I have found that coding the yaml like:
```yaml
  - expression_filter:
      filter:
        if:
          expression: '$hostname == ["sip", "proxysipint", "proxysipintb" ]'
          tasks:
            - set:
                '$.filename': '"kam-int.log"'
        "# else if 1\nelse if":
          expression: '$hostname == ["sipext", "proxysipext" ]'
          tasks:
            - set:
                '$.filename': '"kam-ext.log"'
        "# else if 2\nelse if":
          expression: '$hostname == ["pbxum", "pbxum1", "pbxum1b"]'
          tasks:
            - set:
                '$.filename': '"ast-core.log"'
```
worarounds the problem, but I can't find a better way
