### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by itinneed2022** [voxpupuli/puppet-rsyslog#206]
I've been trying to write a couple of custom config files using this module and I can't seem to figure out how to reference my hiera data correctly. I'm trying to configure my

In my rsyslog.yaml file I have:

```yaml
rsyslog::server::custom_config:
remote_udp_logs:
    priority: 15
    content: |
      ruleset(name="remote_udp"){
        local5.info action(type="omfile" file="/var/log/router_temp/local5info.log" FileCreateMode="0644")
        local7.debug action(type="omfile" file="/var/log/router_temp/local7.log" FileCreateMode="0644")
        local5.debug action(type="omfile" file="/var/log/router_temp/local5debug.log" FileCreateMode="0644")
        local2.debug action(type="omfile" file="/var/log/router_temp/local2debug.log" FileCreateMode="0644")
      }
      ruleset(name="remote_tcp"){
          action(type="omfile" file="/var/log/router_temp/v8temptcp.log" FileCreateMode="0644")
      }

      input(type="imudp" port="514" ruleset="remote_udp")
      input(type="imptcp" port="514" ruleset="remote_tcp")
```

And in my custom_rsyslog.pp file I have:

```puppet
$rsyslog_custom_conf        = hiera('rsyslog::server::custom_config')
include rsyslog::config
rsyslog::server: $rsyslog_custom_conf
```

This does nothing. How do I reference my hiera config in my profile?

**Comment by bschonec** [comment]
Don't forget you need to "include rsyslog::config" somewhere in your Puppet manifest.  Also, do you have indentation issues?  The first line after rsyslog::server::custom_config: isn't indented properly.

This works for me in varying degrees of "This is what I intended."

```

rsyslog::purge_config_files: true   # Purge /etc/rsyslog.d of unmanaged files.
rsyslog::dont_linebreak_actions: true   # Ensure that all rsyslog action lines don't span multiple lines.
rsyslog::config::actions:
  all_logs_to_siem:   
    type: omfwd       
    facility: "*.*;local6.none"  # Log everything EXCEPT the command history
    target: siem.conf       # Create this configuration in its own file.
    config:           
      target: "remote-syslog.example.com"
      protocol: udp   
      port: 514       

rsyslog::override_default_config: false   # Keep /etc/rsyslog.conf intact (for now).
                      
rsyslog::config::global_config:
  FileCreateMode:     
    value: '0640'     
    type: 'legacy'    
  workDirectory:      
    value: '/var/lib/rsyslog'
    #type: 'legacy'   
    #target_file: '/etc/rsyslog.d/10_global.conf'
                      
rsyslog::config::legacy_config:
  auth_none:          
    key: '*.info;local6.none;mail.none;authpriv.none;cron.none'  # Exclude local6 since that's our command line facility.
    value: '/var/log/messages'
  authpriv:           
    key: 'authpriv.*' 
    value: '/var/log/secure'
  mail:               
    key: 'mail.*'     
    value: '-/var/log/maillog'
  cron:               
    key: 'cron.*'     
    value: '/var/log/cron'
  emergency:          
    key: '*.emerg'    
    value: ':omusrmsg:*'
  news:               
    key: 'uucp,news.crit'
    value: '/var/log/spooler'
  boot:               
    key: 'local7.*'   
    value: '/var/log/boot.log'
                      
rsyslog::config::modules:
  imuxsock:           
    config:           
      'SysSock.Use': 'off'   # "off" must be in quotes otherwise it will cast to a boolen.
  imjournal:          
    config:           
      'StateFile': 'imjournal.state'
  immark:                       # --MARK-- message capability
    target: immark.conf         # Create this configuration in its own file.
    config:           
      interval: 300   
```
