### ISSUE TITLE
template list_descriptions not rendering correctly

### ISSUE THREAD

**Issue by b4ldr** [voxpupuli/puppet-rsyslog#252]
When using a `rsyslog::config::templates` of `type: list` the properties are rendered incorrectly. 

for example with the following structure 

```yaml
rsyslog::config::templates:
    json-template:
      type: list
      list_descriptions:
        - constant:
            value: '\"@timestamp\":\"'
          property:
            name: "timereported"
            dateFormat: "rfc3339"
        - constant:
            value: '\",\"message\":\"'
          property:
            name: "msg"
            format: "json"
```

will render as follows

```
template (name="json-template" type="list"
)
{
  constant(value="\"@timestamp\":\""     property(name="timereported" dateFormat="rfc3339" )
  constant(value="\",\"message\":\""     property(name="msg" format="json" )
}
```

however it should render as 

```
template (name="json-template" type="list"
)
{
  constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339" )
  constant(value="\",\"message\":\"")     property(name="msg" format="json" )
}
```
