### ISSUE TITLE
queue.saveonshutdown gives true instead of on

### ISSUE THREAD

**Issue by yorickps** [voxpupuli/puppet-rsyslog#255]
According to the type and reference, queue.saveonshutdown should have a value off 'on' or  'off'

See:
* https://github.com/voxpupuli/puppet-rsyslog/blob/d4eeca67fa41e2f9656814b0a0f68749c30ae635/types/queue/parameters.pp#L24
* https://github.com/voxpupuli/puppet-rsyslog/blob/d4eeca67fa41e2f9656814b0a0f68749c30ae635/REFERENCE.md?plain=1#L2362

My yaml config of the main queue:

```yaml
rsyslog::config::main_queue_opts:
  queue.filename: queue
  queue.maxdiskspace: 1g
  queue.saveonshutdown: on
  queue.spooldirectory: /var/lib/rsyslog
  queue.type: LinkedList 
```

When running puppet however, the value in `50_rsyslog.conf` always produces a `true` value instead of `on`, even with the hieradata mentioned above. Changing to the reference to `queue.saveOnShutdown` has no influence on the outcome.

```
main_queue(
  queue.filename="queue"
  queue.maxdiskspace="1g"
  queue.saveonshutdown="true"
  queue.spooldirectory="/var/lib/rsyslog"
  queue.type="LinkedList"
)
```

Some rsyslog versions error out and won't start when ` queue.saveonshutdown` is a Boolean

**Comment by kenyon** [comment]
Try quoting `on`, like

```yaml
rsyslog::config::main_queue_opts:
  queue.filename: queue
  queue.maxdiskspace: 1g
  queue.saveonshutdown: 'on'
  queue.spooldirectory: /var/lib/rsyslog
  queue.type: LinkedList
```

`on` and `off` are booleans in YAML.
