### ISSUE TITLE
Document ordering / sort algorithm

### ISSUE THREAD

**Issue by jorhett** [voxpupuli/puppet-rsyslog#45]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3
- Ruby: 2.4
- Distribution: ?
- Module version: 

## How to reproduce (e.g Puppet code you use)

```
mail:
    priority: 110
    type: 'omfile'
    facility: 'mail.*'
    config:
      file: '/var/log/maillog'
  cron:
    priority: 111
    type: 'omfile'
    facility: 'cron.*'
    config:
      file: '/var/log/cron.log'
```

## What are you seeing

These rules are places in the rsyslog file after global definitions (priority 10) but before templates, config, etc (20, 30...) To get it to sort properly I have had to use the following:

```
mail:
    priority: 6510
  cron:
    priority: 6511
```

## What behaviour did you expect instead

Priority is shown in the examples as an integer. One assumes it would be sorted like an integer.  I actually kindof like the effect of being able to just make longer numbers to sort within the section-- but the documentation makes no mention of this!
