### ISSUE TITLE
Dependency circle with action class

### ISSUE THREAD

**Issue by Trillon008** [voxpupuli/puppet-rsyslog#47]
Hi 

I believe I tried the most basic setup of this module but everytime I call rsyslog::client::actions I have a dependency circle. 

> (Concat_file[/etc/rsyslog.d/50_rsyslog.conf] => Concat[/etc/rsyslog.d/50_rsyslog.conf] => Rsyslog::Generate_concat[rsyslog::concat::action::mail_logs] => Concat::Fragment[rsyslog::component::action::mail_logs] => Concat_fragment[rsyslog::component::action::mail_logs] => Concat_file[/etc/rsyslog.d/50_rsyslog.conf])

I have these two piece of code: 
#### profile.pp
`class { 'rsyslog::client': }
`
#### common.yaml
```
rsyslog::client::actions:
  mail_logs:
    type: "omfile"
    facility: "mail.*"
    config:
      file: "/var/log/testlog"
```
